### ISSUE TITLE
Setup payment integration

### ISSUE THREAD

**Issue by hswolf** [bctoh/shyfts-sharetribe#2]
- Payment system: Stripe

**Comment by bctoh** [comment]
![Screen Shot 2018-12-03 at 11.27.19 AM.png](https://zube.io/files/sameoriginco/d6bf672a1f308ad0516926c75907a062-screen-shot-2018-12-03-at-11-27-19-am.png)

i get this error when i try to enable payments from the master account. btw feel free to use my account to test it out. 

user: `brian@toh.io`
pw: `shyftsshyfts`

**Comment by bctoh** [comment]
@Tuan-Vinh-To let me know what API keys u need
